
name: Construction d'un projet

on:
  push:
    branches: [ "detached", "master" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name : telechargements des codes sources
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -D maven.test.skip=true -B package --file pom.xml

